spring.datasource.url=jdbc:postgresql://vendexdb.ccfcscsu0whh.us-east-1.rds.amazonaws.com:5432/eleicoes_novo
spring.datasource.username=postgres
spring.datasource.password=EpIfAF7toMZXx9mzlJCr
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.datasource.testWhileIdle=true spring.datasource.validationQuery=SELECT 1
logging.level.org.springframework.web: DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
#http://localhost:8080/swagger-ui.html
